### ISSUE TITLE
is CreateML json format supported?

### ISSUE THREAD

**Issue by pizixie** [pylabel-project/pylabel#106]
Apple's CreateML annotations format.

**Comment by alexheat** [comment]
I have never heard of that. Can you tell me more about it?

**Comment by pizixie** [comment]
ok,waiting...

**Comment by pizixie** [comment]
[What is CreateML JSON?](https://roboflow.com/formats/createml-json)

When Apple released CreateML in 2018 it was a groundbreaking innovation. For the first time, developers could easily train a machine learning model with no code.

**Comment by pizixie** [comment]
I see. Actually, I discovered this CreateML format when using the labelimg annotation tool. 
Afterwards, when using pylabel to split the dataset, I found that it lacked support for this format.

**Comment by alexheat** [comment]
It is not a very common format. It is not supported in this tool. But you can use roboflow to export it to a different format.
