### ISSUE TITLE
Error when i transform a COCO dataset to a YOLO dataset with segmentation = true and cat_id_index = 0

### ISSUE THREAD

**Issue by claudio9russo7** [pylabel-project/pylabel#107]
I got an error when i use segmentation = TRUE and cat_id_index = 0.
The unmerged PR doesn't resolve the problem.
Im using colab as environment

![pylabel1](https://user-images.githubusercontent.com/99536010/236893520-2d520a93-52a2-40b0-8bb9-bc187368c1d2.png)

Im linked the dataset example:
https://we.tl/t-ODWNHXMomH

You will find the .json file in COCO format and images

**Comment by alexheat** [comment]
Thank you for sharing your sample files. I am looking into it now

**Comment by alexheat** [comment]
That unmerged pull request did resolve the issue for me. I integrated it and release a new version https://github.com/pylabel-project/pylabel/releases/tag/v0.1.50. 

Can you give it a try?

**Comment by claudio9russo7** [comment]
I just tried and it's working. Thank you.
