### ISSUE TITLE
cat_id_index for yolov5 to coco format 

### ISSUE THREAD

**Issue by sz2three** [pylabel-project/pylabel#130]
I am using ImportYoloV5 to convert yolo format label to coco format. 
My label only has one classe  ` yoloclasses =( "face") `
But I am not sure the the setting of `cat_id_index `in `yolov2coco.ipynb`.
The default value is `cat_id_index =1,` but should not the value start from `0 `? 

Thanks

**Comment by alexheat** [comment]
Thank you for your question @sz2three. Some frameworks use 0 index, some require the index to start at 1. You can use the   ReindexCatIds method to change the index to 0. See documentation at https://pylabel.readthedocs.io/en/latest/pylabel.html#pylabel.dataset.Dataset.ReindexCatIds
