### ISSUE TITLE
AssertionError: Output shape does not match input shape. Data loss has occured.

### ISSUE THREAD

**Issue by R-N** [pylabel-project/pylabel#140]
Code:
```
dataset = importer.ImportYoloV5("labels", path_to_images="../images")
dataset.splitter.StratifiedGroupShuffleSplit(train_pct=.8, val_pct=.0, test_pct=.2, batch_size=1)
```
Environment:
- Windows 11 64 bit
- Python 3.10
- Jupyter notebook

<details>
<summary>Error:</summary>

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[13], line 1
----> 1 dataset.splitter.StratifiedGroupShuffleSplit(train_pct=.8, val_pct=.0, test_pct=.2, batch_size=1)

File ~\AppData\Roaming\Python\Python310\site-packages\pylabel\splitter.py:223, in Split.StratifiedGroupShuffleSplit(self, train_pct, test_pct, val_pct, weight, group_col, cat_col, batch_size)
    218 df_val["split"] = "val"
    220 df = pd.concat([df_train, pd.concat([df_test, df_val])])
    222 assert (
--> 223     df.shape == df_main.shape
    224 ), "Output shape does not match input shape. Data loss has occured."
    226 self.dataset.df = df
    227 self.dataset.df = self.dataset.df.reset_index(drop=True)

AssertionError: Output shape does not match input shape. Data loss has occured.
</details>

I have no idea what that means and what I should (or shouldn't) do.

**Comment by alexheat** [comment]
@R-N I have resolved the issue in the latest version.

**Comment by R-N** [comment]
@alexheat Thank you. The error went away, but ShowClassSplits is empty. 

![image](https://github.com/pylabel-project/pylabel/assets/1442761/8452d524-4ee3-46d0-b11f-bd849e6b7379)

**Comment by R-N** [comment]
I see the problem. dataset.df["cat_name"] is empty

**Comment by R-N** [comment]
Okay it seems to be empty from the start, right after loading, so it's a different issue.

![image](https://github.com/pylabel-project/pylabel/assets/1442761/0ddbd7aa-e521-446a-bb7a-b4a7f9ffd059)
