### ISSUE TITLE
ValueError: not enough values to unpack (expected 5, got 0).

### ISSUE THREAD

**Issue by isspid** [pylabel-project/pylabel#29]
I think this happens with images that don't have annotations, meaning their respective .txt files are empty.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_24072/4001401144.py in <module>
      9 print("Here")
     10 dataset1 = importer.ImportYoloV5(path=path_to_annotations, path_to_images=path_to_images, cat_names=yoloclasses,
---> 11     img_ext="jpeg", name="view, cut, plan")
     12 print("Here 2")
     13 

~\Anaconda3\envs\yolov5\lib\site-packages\pylabel\importer.py in ImportYoloV5(path, img_ext, cat_names, path_to_images, name)
    300                     width_norm,
    301                     height_norm,
--> 302                 ) = line.split()
    303                 row["img_folder"] = path_to_images
    304                 row["img_filename"] = filename.name.replace("txt", img_ext)

ValueError: not enough values to unpack (expected 5, got 0)

```

**Comment by alexheat** [comment]
Hello @isspid , thank you for reporting the issue. You are right about the root cause of the issue. In particular I was able to repro this when the text file had a line break (empty line) but no annotations. (If the file is totally empty without line breaks the error doesn't occur. 

I will try and release a fix for it today.

**Comment by isspid** [comment]
Can i help in any way? If you point me in a direction maybe I could try and submit a PR?

**Comment by alexheat** [comment]
Hello @isspid thank you. I have fixed that particular issue but I am testing if the empty values cause other issues. 

What is the full task you are trying to accomplish? Do you want to convert to another format? If I will test that before releasing a new version.

Is there a way you can share your dataset so I can test with that one?

**Comment by isspid** [comment]
I was trying to convert from YOLOv5 to COCO json. 
[This is a sample of the dataset.](https://drive.google.com/file/d/1834sAmgZvNd_nBe7UpImAVWQb1o9_CyU/view?usp=sharing)

**Comment by alexheat** [comment]
Thank you. I found some issues in the coco output with the empty annotation files so I need to make some more fixes before I release a new version.

**Comment by alexheat** [comment]
Hello @isspid , I released version [v0.1.33] that should fix your issue. Can you give it a try?

**Comment by isspid** [comment]
The problem with the .txt files that didn't have annotations is fixed. I noticed something else that doesn't add up:
![image](https://user-images.githubusercontent.com/91065022/155880524-dc2e9c67-41a9-4dc1-9e40-0c9a5a0e7e83.png)
I don't know if the problems are related but there are 3 classes and 4 numbers reporting the counts. If this needs its own issue please let me know.

**Comment by alexheat** [comment]
Let me explain those numbers. Each annotation is stored as a row in a dataframe. (dataframe.df)

Images with no annotations will have a single row, but the class fields will be blank. What you are seeing above is 73 instances of the null class. (73 images with no classes.) If you have 73 images with no classes then this would be by design.

**Comment by isspid** [comment]
Okay got it, thanks for the explanation. Closing as solved.
