### ISSUE TITLE
!_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by robmarkcole** [pylabel-project/pylabel#34]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/11855322/158182809-c35c701f-4cb5-4501-a1bb-bb3c7ef74c94.png">

```python
from IPython.display import Image, display
display(dataset.visualize.ShowBoundingBoxes(100))

---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
/Users/robin/Documents/GitHub/oil-storage-tank/pylabel.ipynb Cell 3' in <cell line: 2>()
      [1](vscode-notebook-cell:/Users/robin/Documents/GitHub/oil-storage-tank/pylabel.ipynb#ch0000002?line=0)[ from IPython.display import Image, display
----> ]()[2](vscode-notebook-cell:/Users/robin/Documents/GitHub/oil-storage-tank/pylabel.ipynb#ch0000002?line=1)[ display(dataset.visualize.ShowBoundingBoxes(100))

File ~/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py:27, in Visualize.ShowBoundingBoxes(self, img_id, img_filename)
     ]()[25](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=24)[ full_image_path = str(Path(ds.path_to_annotations, df_single_img_annots.iloc[0].img_folder, df_single_img_annots.iloc[0].img_filename))
     ]()[26](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=25)[ img = cv2.imread(str(full_image_path))
---> ]()[27](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=26)[ img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
     ]()[29](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=28)[ labels = []
     ]()[30](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=29)[ bboxes = []

error: OpenCV(4.5.5) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor']()
```

 I was suspicious the img_path col is empty, but updating this doesn't resolve

**Comment by alexheat** [comment]
Thank you Rob. I will fix this in the next update. It looked like you fixed you .json file. How id you do that? Can you share your fixed file so I can test that it works?

**Comment by alexheat** [comment]
@robmarkcole , I see the issue. It is actually working as expected. But I also see why it confusing. The path_to_images variable populates the img_folder column of the dataframe. (The img_path column is not actually used for anything yet.)

And per the documentation of the ImportCoco method, the path should be relative to the location of the JSON file. https://pylabel.readthedocs.io/en/latest/pylabel.html#module-pylabel.importer 

> path_to_images (str) – The path to the images relative to the json file. If the images are in the same directory as the JSON file then omit this parameter. If the images are in a different directory on the same level as the annotations then you would set path_to_images=’../images/’

If the images are in the same folder as the json file then this field can be left blank.

**Comment by robmarkcole** [comment]
Thanks for the clarification, will close
