### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by robmarkcole** [pylabel-project/pylabel#35]
Occurs on calling visualize when bounding boxes have nan values:

```python
from IPython.display import Image, display
display(ds.visualize.ShowBoundingBoxes(5))

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/robin/Documents/GitHub/oil-storage-tank/pylabel.ipynb Cell 7' in <cell line: 2>()
      [1](vscode-notebook-cell:/Users/robin/Documents/GitHub/oil-storage-tank/pylabel.ipynb#ch0000002?line=0)[ from IPython.display import Image, display
----> ]()[2](vscode-notebook-cell:/Users/robin/Documents/GitHub/oil-storage-tank/pylabel.ipynb#ch0000002?line=1)[ display(ds.visualize.ShowBoundingBoxes(5))

File ~/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py:34, in Visualize.ShowBoundingBoxes(self, img_id, img_filename)
     ]()[32](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=31)[ for index, row in df_single_img_annots.iterrows():
     ]()[33](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=32)[     labels.append(row['cat_name'])
---> ]()[34](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=33)[     bboxes.append([int(row['ann_bbox_xmin']),int(row['ann_bbox_ymin']),int(row['ann_bbox_xmax']),int(row['ann_bbox_ymax'])])
     ]()[36](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=35)[ img_with_boxes = bbv.draw_multiple_rectangles(img, bboxes)
     ]()[37](file:///Users/robin/Documents/GitHub/oil-storage-tank/venv/lib/python3.9/site-packages/pylabel/visualize.py?line=36)[ img_with_boxes = bbv.add_multiple_labels(img_with_boxes, labels, bboxes)

ValueError: cannot convert float NaN to integer]()
```

I guess this occurs as I have images with zero annotations

**Comment by alexheat** [comment]
Yes, I think you are correct. I did some work to make the core import and export work for images with zero annotations but I did not test all of the features. I will try to fix it in the next update. The simplest solution would be to just show the image with no boxes.

**Comment by alexheat** [comment]
Hi @robmarkcole , I released v 0.1.34 which should fix the error when viewing the bounding boxes if there are no annotations.

**Comment by Interpause** [comment]
This issue seems to occur when exporting datasets containing images with no annotations

**Comment by alexheat** [comment]
@Interpause are you hitting a problem when exporting? Or when drawing the bounding boxes? 

Would you be able to share your dataset that repos the problem?

**Comment by Interpause** [comment]
The problem is during exporting. When importing a Coco dataset (`data_val = importer.ImportCoco(path)`) that contains images with no annotations, `data_val.df.cat_id` appears to be the string `nan` (not `np.nan`) for the unannotated images. I got around it by filtering via `data_val.df = data_val.df[data_val.df.cat_id != 'nan']`.

**Comment by alexheat** [comment]
Hello @Interpause. Yes there can be issues with images that don't have an annotations, but I fixed some bugs and verified that it worked with my test dataset. Would you be able to share your dataset that has the problem? 

You have a good workaround but I would like to make it work for images that don't have annotations because that is a valid way to make a dataset for training.

**Comment by alexheat** [comment]
Working on this PR which should fix the issue https://github.com/pylabel-project/pylabel/pull/44

**Comment by alexheat** [comment]
Hello @Interpause. I have release v0.1.36 that should fix the issue https://github.com/pylabel-project/pylabel/releases/tag/v0.1.36

Could you give it a try? Thanks for identifying the root cause of the issue. The nan values should not be converted to strings any longer.

**Comment by Interpause** [comment]
yup it works. thanks!
