### ISSUE TITLE
Only 1 label is imported as a result of importer.ImportYoloV5

### ISSUE THREAD

**Issue by pmk-gh** [pylabel-project/pylabel#40]
When YOLO annotations are imported and a picture has more than 1 annotation (e.g., `2021-07-03T06-33-53-frame_0000.jpeg` file in _Squirrels and Nuts_ dataset used in the sample Jupyter Notebook), the amount of imported annotations is correct, but all of them represent the last annotation from the corresponding .txt file.

**Environment:** Python 3.9, pylabel 0.1.34

Example:

content of `2021-07-03T06-33-53-frame_0000.txt` file:

1 0.7305 0.8444 0.0505 0.1167
1 0.8003 0.8255 0.0547 0.0917
1 0.8784 0.7824 0.0401 0.0981

content of `img_df` corresponding to the annotation file:

![image](https://user-images.githubusercontent.com/101800592/158786696-7b54f893-2b2a-43b5-bb5a-2e8e59f995f9.png)

**Solution:** I analyzed the case, and I can see that the fix should be to replace line 374 in `importer.py` (the line is `d[row_id] = row`) with `d[row_id] = dict(row)`.

**Comment by alexheat** [comment]
Hi @pmk-gh , thank you for finding the fix! This must be a semi-new bug because it did not have this problem before. I will make the fix.

**Comment by pmk-gh** [comment]
Hi @alexheat, yes, it looks good.
