### ISSUE TITLE
ExportToCoco() saves category_id as string instead of integer

### ISSUE THREAD

**Issue by dnth** [pylabel-project/pylabel#46]
I exported my VOC labels into COCO and find that the `id` and `category_id` values in the .json file are inconsistent.

In the .jsons file we have `"id": 0`
```
"categories": [
        {
            "id": 0,
            "name": "LP",
            "supercategory": null
        }
    ]
```

But in the annotations I find `"category_id": "0"`

```
{
            "image_id": 208,
            "id": 112,
            "segmented": "0",
            "bbox": [
                759.0,
                475.0,
                27.0,
                26.0
            ],
            "area": 702.0,
            "segmentation": null,
            "iscrowd": 0.0,
            "pose": "Unspecified",
            "truncated": "0",
            "category_id": "0",
            "difficult": "0"
        }
```
I had to manualy change the `"category_id": "0"` to `"category_id": 0` use the annotations and train a model. Is this a bug?

**Comment by alexheat** [comment]
Hi @dnth Diskson, thank you for reporting the issue. You are right, they should be ints. (I am not sure if this issue has always been there or not, but no one else has mentioned it.) 

And per our chat, thank you offering to work on the PR yourself to fix the issue. Here are a few tips to help you:
- There is a spec for the coco schema here https://cocodataset.org/#format-data (I didn't have this when I first started this project.) There may be issues with some of the other fields so if you are able to fix any other similar issues that would be great
- The code that needs to be fixed is in the exporter.py file for example here https://github.com/pylabel-project/pylabel/blob/dev/pylabel/exporter.py#L697 and here https://github.com/pylabel-project/pylabel/blob/dev/pylabel/exporter.py#L706 
- That coco exporter code is one of the parts that I didn't write originally so I am not sure why it is written the way it is. As I recall there is some repeated code and you may have to apply the fix in multiple places. 
Thanks again! Let me know if you have any questions.

**Comment by alexheat** [comment]
This should be fixed in release https://github.com/pylabel-project/pylabel/releases/tag/v0.1.37

**Comment by dnth** [comment]
Thank you!
