### ISSUE TITLE
Example notebook error

### ISSUE THREAD

**Issue by robmarkcole** [pylabel-project/pylabel#5]
Running `import2.ipynb` will result in error:

```
dataset.df = dataset.test(dataset.df)

AttributeError: 'Dataset' object has no attribute 'test'
```

**Comment by alexheat** [comment]
Thank you @robmarkcole . I removed that extraneous cell and it runs without an error. This is the direct link to that notebook by the way https://github.com/pylabel-project/samples/blob/main/coco2voc.ipynb.

Thanks again for report this we really appreciate it.

**Comment by alexheat** [comment]
I'm closing the issue because I think that it's fixed. But it you see any other problems let us know
