### ISSUE TITLE
How to display confidence key in json?

### ISSUE THREAD

**Issue by wiseshahab** [pylabel-project/pylabel#60]
Hi, Sir Thank you for this solution it helped me a lot I want to add confidence against every bounding box. Also when I import confidence in txt files from yolov5 like "0 0.1 0.3 0.5 0.6 0.83" the last figure is confidence the script gives an error of packing extra parameters.

**Comment by alexheat** [comment]
Hi thank you for the feedback. I have a few questions for you: 
- What is your desired goal of what will happen with the confidence number? Even if I could resolve the error, I am not sure what would happen to that value once your export it to other formats. 
- Is that extra confidence column an official part of the Yolo data format?
