### ISSUE TITLE
Cannot import PASCAL VOC dataset

### ISSUE THREAD

**Issue by emillundh** [pylabel-project/pylabel#61]
The dataset is in PASCAL VOC format, as exported by CVAT. When importing, I receive the traceback
```
Traceback (most recent call last):
  File "path\to\convert_annotations.py", line 5, in <module>
    voc_data = importer.ImportVOC(voc_folder)
  File "path\to\.venv\lib\site-packages\pylabel\importer.py", line 207, in ImportVOC
    row["ann_pose"] = _GetValueOrBlank(o.find("pose"))
  File "path\to\.venv\lib\site-packages\pylabel\importer.py", line 27, in _GetValueOrBlank
    return element.text
AttributeError: 'NoneType' object has no attribute 'text'
```
Here is an example of an annotation xml exported by CVAT:
```
<?xml version="1.0"?>
<annotation>
<folder>myfolder</folder>
<filename>myfile.png</filename>
<source>
<database>Unknown</database>
<annotation>Unknown</annotation>
<image>Unknown</image>
</source>
<size>
<width>5328</width>
<height>4608</height>
<depth/>
</size>
<segmented>0</segmented>
<object>
<name>my_object</name>
<truncated>0</truncated>
<occluded>0</occluded>
<difficult>0</difficult>
<bndbox>
<xmin>127.06</xmin>
<ymin>632.19</ymin>
<xmax>161.12</xmax>
<ymax>666.86</ymax>
</bndbox>
<attributes>
<attribute>
<name>rotation</name>
<value>0.0</value>
</attribute>
</attributes>
</annotation>```

**Comment by alexheat** [comment]
Hello thank you for reporting the issue. Could you possibly send me the zipped up dataset so I can repro and debug the issue?

**Comment by emillundh** [comment]
> Hello thank you for reporting the issue. Could you possibly send me the zipped up dataset so I can repro and debug the issue?

I'll be happy to, but I might make one that's clean from any business details first. In the meantime I can report that my problem is solved if the method _GetValueOrBlank is modified like its own docstring is implying (?),
```
    if user_input == None:
        try:
            return element.text
        except AttributeError:
            return ""
    else:
        return user_input
```

**Comment by alexheat** [comment]
Hello. Have you confirmed that this will resolve the issue or is it a question?

**Comment by emillundh** [comment]
Sorry for being unclear. Yes, I have confirmed it. With this change in place, my Pascal VOC dataset could be imported.

**Comment by alexheat** [comment]
Oh great. Would you be able to submit a pull request to check in your change?

**Comment by alexheat** [comment]
Thank you @emillundh. I have integrated your PR and release v41 with your fix https://github.com/pylabel-project/pylabel/releases/tag/v0.1.41. Could you please do a test with this released package and confirm if it works for your dataset?

**Comment by emillundh** [comment]
It does, thank you for your effort!
