### ISSUE TITLE
Is instance segmentation support planned?

### ISSUE THREAD

**Issue by Robotatron** [pylabel-project/pylabel#65]
Is instance segmentation support planned?
YOLO5 now supports segmentation

**Comment by alexheat** [comment]
Hi @Robotatron I want to look into this. Would you be able to help? Can you share any resources on the Yolo5 segmentation with segmentation samples in other formats like Coco that would make sense to transform into Yolo?

**Comment by mosolab** [comment]
Hi! Thanks for tool.
 I’m interested too and could provide you examples.
Please let me know how to share it.

**Comment by alexheat** [comment]
Hi thank you. Can you share links on this issue thread?

**Comment by Robotatron** [comment]
@alexheat 
> Hi @Robotatron I want to look into this. Would you be able to help? Can you share any resources on the Yolo5 segmentation with segmentation samples in other formats like Coco that would make sense to transform into Yolo?

Sure. Here is an official YOLO5 repo to convert COCO segmentation to YOLO5 format (works with YOLO7 as well) https://github.com/ultralytics/JSON2YOLO/blob/master/general_json2yolo.py

If you'd like to test training a YOLO5 for segmentation it's exactly the same as for object detection but using train.py from their "segment" folder from the repo: https://github.com/ultralytics/yolov5/tree/master/segment

Let me know if there is other information I could help with

**Comment by alexheat** [comment]
@Robotatron , @mosolab , I have written a proposal for how I will implement the conversion of segmentation conversion. If you have time please take a look and let me know if you have any feedback https://github.com/pylabel-project/pylabel/discussions/72

**Comment by alexheat** [comment]
I have release version .44 with support for converting Coco segmentation annotations to Yolo segmentation format. You can see a demonstration in this notebook https://github.com/pylabel-project/samples/blob/main/coco2yolosegmentation.ipynb

**Comment by sudheer-palaparambil** [comment]
Thanks @alexheat  for your immediate response and time. I downloaded the latest pylabel 0.1.44 and tried with some Coco segmentation annotations (done in makesense.ai). I got some broken annotations in some images. Attached both actual image and PyLabel generated image.
![Actual](https://user-images.githubusercontent.com/9995485/212623133-82eb3266-06cb-42c4-b1ad-291eca500b9b.png)
![PyLabel generated](https://user-images.githubusercontent.com/9995485/212623159-9310404a-ed6b-496e-b11b-6fbac663e23e.png)

**Comment by sudheer-palaparambil** [comment]
Thanks @alexheat for your immediate response and time. I downloaded the latest pylabel 0.1.44 and tried with some Coco segmentation annotations (done in makesense.ai). I got some broken annotations in some images. Attached both actual image and PyLabel generated image.
![Actual](https://user-images.githubusercontent.com/9995485/212623784-dffd843d-ebc6-4b11-844e-b07da7f34da1.png)
![PyLabel generated](https://user-images.githubusercontent.com/9995485/212623809-f0889e8f-811b-4045-9d7c-00007f1554a5.png)

**Comment by alexheat** [comment]
Thank you @sudheer-palaparambil , can you explain what you mean by broken images? I do not see what is broken. Do you mean the dotted lines? I don't see how those could have been added by PyLabel because it is only touching the annotations.

Can you provide the steps that you are doing to get those lines and the dataset like you did last time? Also, what tool are you using the rendering the images?

**Comment by sudheer-palaparambil** [comment]
Hi @alexheat,

I mean that gap in the bottom annotation line.
I executed the following source. 

<---------- Beginning
from pylabel import importer
import os 

os.makedirs("data", exist_ok=True)
#Specify path to the coco.json file
path_to_annotations = "data/project-22124.json"
#Specify the path to the images (if they are in a different folder than the annotations)
path_to_images = "images/"

#Import the dataset into the pylable schema 
dataset = importer.ImportCoco(path_to_annotations, path_to_images=path_to_images, name="Segmentation")
dataset.df.head(5)

dataset.path_to_annotations = "data/yolo"
dataset.export.ExportToYoloV5(segmentation=True)[1]
<----------- End

I copied the labels generated from training\labels folder and uploaded it along with the images to roboflow. The above images are rendered in roboflow. For annotation I used makesense.ai

The first images in the previous mail is rendred when I uploaded images and Coco-JSON generated by makesense.ai

Thank you

**Comment by alexheat** [comment]
I see it now thank you. Can you share the original annotations as well? I want to investigate what is causing the gap by looking at the actual annotation coordinates

**Comment by sudheer-palaparambil** [comment]
Herewith attaching the dataset containing original annotations, PyLabel generated annotations and rendered images as well. 
[Dataset.zip](https://github.com/pylabel-project/pylabel/files/10441825/Dataset.zip)

**Comment by mosolab** [comment]
@alexheat also on this now. I could convert it but would like also to visualise labelling.
Could converted labelling be visualised with pylabel?

**Comment by alexheat** [comment]
Thank you @sudheer-palaparambil , I have released v45 that fixes the issue. The issue was an extra space the end of each line. I am not sure it it really broken the annotations or just the visual on roboflow but the issue is fixed. Thank you for you help to test it.

**Comment by mosolab** [comment]
@alexheat here is my example. looks like not full connected
<img width="356" alt="Screenshot 2023-01-18 at 20 41 04" src="https://user-images.githubusercontent.com/4863793/213278758-74a9b23a-c90b-4dd1-8e0e-1e42897b39b4.png">

**Comment by alexheat** [comment]
Hi, are you use using the latest version of the package:
pip install pylabel==0.1.45

**Comment by mosolab** [comment]
Yes, you are right. I had 0.1.44.
Just checked 0.1.45 and it works and looks great!
Thanks!

**Comment by alexheat** [comment]
Thank you everyone

**Comment by Robotatron** [comment]
you are awesome, thanks!
