### ISSUE TITLE
Issue if image has no bounding boxes

### ISSUE THREAD

**Issue by n12iB** [pylabel-project/pylabel#66]
Hi,
I was converting from YOLO to VOC, and it seems that if an image doesnt have any bounding boxes, then it causes an error to occur. This is the error: `ValueError: invalid literal for int() with base 10: '`. This arises in the exporter.py script.

**Comment by alexheat** [comment]
hello @n12iB . This issue was resolved for some other formats but the voc exporter is the least popular so thank you for testing it and raising the issue. Could you possibly share the dataset that I can use to repro the issue and validate the fix?

**Comment by n12iB** [comment]
@alexheat np, I was using this dataset https://www.kaggle.com/datasets/sakshamjn/vehicle-detection-8-classes-object-detection?resource=download

**Comment by alexheat** [comment]
@n12iB , I released a new version of the package that should resolve the issue. Can you give it a try?

While it will resolve the issue, I am not sure if the output is a valid voc xml file or not. But go ahead and give it a try.

I am curious to know what framework you are using that uses voc files.

**Comment by alexheat** [comment]
I take that back, it is not published yet. I need to figure something out...

**Comment by n12iB** [comment]
@alexheat  dont worry about. I was just messing around with the library to see how it works and happened to choose voc. So it isnt for any framework that I am using, and it is fine if the issue is fixed later. I just thought you would like to know.

**Comment by alexheat** [comment]
Thanks for flagging the issue
