### ISSUE TITLE
Does PyLabel support polygon annotation ?

### ISSUE THREAD

**Issue by sudheer-palaparambil** [pylabel-project/pylabel#73]
Hello,
 
   Does PyLabel convert coco-json to Yolov5 PyTorch txt format ?  I have annotated some image using makesense.ai with the following Coco-JSON format

{"info":{"description":"my-project-name"},"images":[{"id":1,"width":3072,"height":4096,"file_name":"IMG20221222113909.jpg"}],"annotations":[{"id":0,"iscrowd":0,"image_id":1,"segmentation":[[1328.987654320987,1200.987654320987,1284.7407407407402,1229.4320987654314,1249.9753086419746,1257.876543209876,1164.6419753086413,1295.8024691358019,1088.7901234567896,1298.9629629629624,1050.8641975308637,1295.8024691358019,1060.3456790123453,1352.6913580246908,1249.9753086419746,1333.7283950617277,1344.7901234567894,1270.518518518518]],"bbox":[1050.8641975308637,1200.987654320987,293.92592592592564,151.7037037037037],"area":17625.098613016293},{"id":1,"iscrowd":0,"image_id":1,"segmentation":[[1543.9012345679005,1191.5061728395056,1490.172839506172,1213.629629629629,1464.8888888888882,1248.3950617283945,1417.4814814814808,1298.9629629629624,1385.876543209876,1321.0864197530857,1370.0740740740735,1324.2469135802462,1379.555555555555,1406.4197530864192,1569.1851851851845,1384.2962962962956,1727.209876543209,1479.1111111111104,1761.9753086419744,1428.5432098765425,1676.6419753086411,1336.8888888888882,1594.4691358024684,1223.1111111111106]],"bbox":[1370.0740740740735,1191.5061728395056,391.90123456790093,287.60493827160485],"area":51686.638012498006}],"categories":[{"id":1,"name":"Hanger"}]}

Can I convert this to Yolov5 PyTorch txt format ?

Thank you.

**Comment by alexheat** [comment]
Thank you, it doesn't support this yet but I got a few requests so I am going to work on it. If would be comfortable sharing your dataset and images that would be helpful for my dev and testing but in not I will look for other examples.

**Comment by sudheer-palaparambil** [comment]
Thanks for your prompt reply. Herewith I am attaching a small dataset. I don't have a large dataset, I am just doing some tests. Thank and regards.
[dataset.zip](https://github.com/pylabel-project/pylabel/files/10416366/dataset.zip)

**Comment by alexheat** [comment]
Thank you @sudheer-palaparambil , I have written a [proposal](https://github.com/pylabel-project/pylabel/discussions/72) for how I will implement the conversion of segmentation conversion. If you have time please take a look and let me know if you have any feedback https://github.com/pylabel-project/pylabel/discussions/72

**Comment by alexheat** [comment]
You can track progress in this related issue https://github.com/pylabel-project/pylabel/issues/65
