### ISSUE TITLE
Conversion from coco to YoloV5 fails

### ISSUE THREAD

**Issue by mhrahimi** [pylabel-project/pylabel#82]
importer.ImportCoco(path_to_annotations).ExportToYoloV5()
AttributeError: 'Dataset' object has no attribute 'ExportToYoloV5'

**Comment by alexheat** [comment]
Hi thank you. Can you provide more details about your dataset or code that is not working? I checked and this sample notebook is still working https://github.com/pylabel-project/samples/blob/main/coco2yolov5.ipynb 

You can open it in Google colab with this URL https://githubtocolab.com/pylabel-project/samples/blob/main/coco2yolov5.ipynb

**Comment by alexheat** [comment]
Not repro
