### ISSUE TITLE
add in tqdm for progress tracking

### ISSUE THREAD

**Issue by geezacoleman** [pylabel-project/pylabel#83]
Thanks for developing a very handy and easy to use tool. 

I was recently trying to convert a dataset of ~5500 images from YOLO to VOC and it took about 15 minutes on my computer. It seemed to work fine in the end, but having some form of progress indication (i.e. `tqdm`) would be helpful to know it is working correctly.

**Comment by alexheat** [comment]
Sounds like a good idea. I will look into it. If you have any tips about integrating tqdm into a package please share them

**Comment by alexheat** [comment]
I have added tqdm support in v46 https://github.com/pylabel-project/pylabel/releases/tag/v0.1.46 

Give it a try

**Comment by geezacoleman** [comment]
thanks for adding this in so quickly - tweaked your implementation slightly so it has endpoints now for time estimates in #87

**Comment by alexheat** [comment]
Thank you @geezacoleman . Your latest checkin passed the tests and I have released in in v47 https://github.com/pylabel-project/pylabel/releases/tag/v0.1.47 

Thanks again for making a contribution!

**Comment by geezacoleman** [comment]
No worries, glad it was helpful and thanks for working on pylabel!
