### ISSUE TITLE
vscode compatibility

### ISSUE THREAD

**Issue by jonaden94** [pylabel-project/pylabel#84]
First of all, this is a very nice tool, especially the labeling aid! Unfortunately I can only get it working on colab. If I try to use the labeling aid on vscode, it does not work but also does not throw any errors. It just fails silently. I made sure that all jupyter settings are configured correctly.

**Comment by alexheat** [comment]
Hello. I also use VS Code and don't know how to get get the widget to show up in VS Code. 

I am using a seperate widget called jupyter-bbox-widget @  https://github.com/gereleth/jupyter-bbox-widget

**Comment by jonaden94** [comment]
Thank you for the response. You are right it seems to be a problem with the widget in general on vscode. I will stick to colab for now!
