### ISSUE TITLE
I want extract a specific category in coco stuff dataset

### ISSUE THREAD

**Issue by goldeneave** [pylabel-project/pylabel#90]
as the title said, in your sample, it seems I could only extract some image randomly, and then generate coressponding annotation file, however, it could not satisfy my needs, is there exist some solutions?

**Comment by alexheat** [comment]
Hello, please see this notebook with a sample of how to extract a specific class https://github.com/pylabel-project/samples/blob/main/coco_extract_subset.ipynb

**Comment by goldeneave** [comment]
thanks for your reply, I read your tutorial you write in your repo, however, I want generate a subset in a specific category, your demo notebook extract some images randomly, and what about move corresponding image file to a new folder, THANKS AGAIN!

**Comment by alexheat** [comment]
Is your goal to extract the image files into a folder with only the images of a certain class? Or to view all of the image in the notebook?

**Comment by goldeneave** [comment]
I sent you an email and described my isue more detailed in it. For your queation, I just wanna generate a data subset, and I means moved image files into a new folder and generate a new annotation file either

**Comment by goldeneave** [comment]
Hello, I solved the problem, thanks for you time, and your excellent job, it really help me.

**Comment by alexheat** [comment]
I'm glad it was helpful
