### ISSUE TITLE
Class categories not correct after conversion from coco to yolo format.

### ISSUE THREAD

**Issue by athinail** [pylabel-project/pylabel#91]
I have a coco dataset. I converted it to yolo format and visualized the annotations (see attached images). The class labels are not correct anymore. What shall I do?

![coco](https://user-images.githubusercontent.com/81266995/222221072-85620495-b63d-418e-8834-94a2f1503c12.png)
![yolo](https://user-images.githubusercontent.com/81266995/222221060-c30c8e5e-5f2e-49e4-95fa-decc610e484a.png)

**Comment by alexheat** [comment]
Hi can you share your data and sample code/notebook. That will help me
investigate

**Comment by athinail** [comment]
My apologies, I found the issue, I made an error during visualizing YOLO annotations.

**Comment by alexheat** [comment]
Thanks for following up to confirm that it works
